server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 49.234.6.178:8848 #nacos服务地址
    gateway:
      routes: #路由id可以有多个，所以你看到id前面是 -
        - id: user-service #给路由规则命名一个id，这个id必须唯一。命名随意
          uri: lb://userservice #路由目的地，建议写服务名。当然你也可以写成http://ip地址:端口
          predicates: #路由断言，判断请求是否符合规则。符合规则的才会被路由到目的地，路由断言可以有多个
            - Path=/user/** #路径断言，判断路径是否以/user开头，如果是则符合规则，就会路由到上面URI属性指定的地方
#          filters:
#            - AddRequestHeader=Truth,Itcast is freaking aowsome!
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
#            - After=2037-01-20T17:42:47.789-07:00[Asia/Shanghai] #在这个时间点之后才能访问
            - Before=2037-01-20T17:42:47.789-07:00[Asia/Shanghai] #在这个时间点之前才能访问
      default-filters:
        - AddRequestHeader=Truth,Itcast is freaking aowsome!
